version: '2.1'

services:
    php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        working_dir: /var/www/app
        volumes:
            - './:/var/www/app'
        env_file: .env

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=raw_events
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
