version: '2.1'

services:
    php:
        image: php:7.0-cli
        working_dir: /var/www/app
        volumes:
            - './:/var/www/app'
        environment:
            - APP_GITHUB_TOKEN=b38c215c506a4d6c49a8f717e5f00dde9ae09593

    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=raw_events
            - MYSQL_USER=app
            - MYSQL_PASSWORD=app
