services:
    app.command.repository_event.fetch:
        class: AppBundle\Command\RepositoryEvent\Fetch
        arguments: ["@use_cases.fetch_repo_events.use_case"]
        tags:
            - { name: console.command }

    app.command.feed.summary:
        class: AppBundle\Command\Feed\Summary
        arguments: ["@use_cases.fetch_feeds.use_case", '%temp_user_uuid%']
        tags:
            - { name: console.command }

    infrastructure.github.event_fetcher:
        class: Infrastructure\Github\EventFetcher
        arguments:
            - '%github_login%'
            - '%github_password%'

    infrastructure.dbal.feed_fetcher:
        class: Infrastructure\DBAL\FeedFetcher
        arguments:
            - '@connection'

    use_cases.fetch_repo_events.use_case:
        class: UseCases\FetchRepoEvents\UseCase
        arguments:
            - "@infrastructure.github.event_fetcher"
            - "@infrastructure.dbal.event_persister"

    use_cases.fetch_feeds.use_case:
        class: UseCases\FetchFeeds\UseCase
        arguments: ["@infrastructure.dbal.feed_fetcher"]

    connection:
        class: Doctrine\DBAL\Connection
        factory: ["Doctrine\\DBAL\\DriverManager", "getConnection"]
        arguments:
          - driver: pdo_mysql
            dbname: '%db_name%'
            user: '%db_user%'
            password: '%db_password%'
            host: '%db_host%'
            serverVersion: '5.7'

    app.command.dbal.create_schema:
        class: AppBundle\Command\DBAL\CreateSchema
        arguments:
            $dbal: '@connection'
            $dbName: '%db_name%'
        tags:
          - { name: console.command }

    app.command.feed.create:
        class: AppBundle\Command\Feed\Create
        arguments:
            - "@use_cases.create_feed.use_case"
            - "%temp_user_uuid%"
        tags:
            - { name: console.command }

    use_cases.create_feed.use_case:
        class: UseCases\CreateFeed\UseCase
        arguments:
            - "@infrastructure.dbal.feed_persister"

    infrastructure.dbal.feed_persister:
        class: Infrastructure\DBAL\FeedPersister
        arguments:
            - "@connection"

    infrastructure.dbal.event_persister:
        class: Infrastructure\DBAL\EventPersister
        arguments:
            - "@connection"
