services:
    app.command.fetch_repo_events:
        class: AppBundle\Command\FetchRepoEvents
        arguments: ["@use_cases.fetch_repo_events.use_case"]
        tags:
            - { name: console.command }

    app.command.fetch_feeds:
        class: AppBundle\Command\FetchFeeds
        arguments: ["@use_cases.fetch_feeds.use_case", '%temp_user_uuid%']
        tags:
            - { name: console.command }

    infrastructure.github.event_fetcher:
        class: Infrastructure\Github\EventFetcher
        arguments:
            - '%github_login%'
            - '%github_password%'

    infrastructure.dbal.feed_fetcher:
        class: Infrastructure\DBAL\FeedFetcher
        arguments:
            - '@connection'

    use_cases.fetch_repo_events.use_case:
        class: UseCases\FetchRepoEvents\UseCase
        arguments: ["@infrastructure.github.event_fetcher"]

    use_cases.fetch_feeds.use_case:
        class: UseCases\FetchFeeds\UseCase
        arguments: ["@infrastructure.dbal.feed_fetcher"]

    connection:
        class: Doctrine\DBAL\Connection
        factory: ["Doctrine\\DBAL\\DriverManager", "getConnection"]
        arguments:
          - driver: pdo_mysql
            dbname: '%db_name%'
            user: '%db_user%'
            password: '%db_password%'
            host: '%db_host%'
            serverVersion: '5.7'

    AppBundle\Command\CreateSchema:
        class: AppBundle\Command\CreateSchema
        arguments:
            $dbal: '@connection'
            $dbName: '%db_name%'
        tags:
          - { name: console.command }
