services:
    _defaults:
        public: false

    AppBundle\Command\:
        resource: '../../src/AppBundle/Command'
        public: true
        autowire: true
        autoconfigure: true

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']

    AppBundle\Github\Client:
        arguments:
            $githubLogin: '%github_login%'
            $githubPassword: '%github_password%'

    Doctrine\DBAL\Connection:
        class: Doctrine\DBAL\Connection
        factory: ["Doctrine\\DBAL\\DriverManager", "getConnection"]
        arguments:
          - driver: pdo_mysql
            dbname: '%db_name%'
            user: '%db_user%'
            password: '%db_password%'
            host: '%db_host%'
