services:
    app.command.fetch_repo_events:
        class: AppBundle\Command\FetchRepoEvents
        arguments: ["@use_cases.fetch_repo_events.use_case"]
        tags:
            - { name: console.command }

    infrastructure.github.event_fetcher:
        class: Infrastructure\Github\EventFetcher
        arguments:
            - '%github_login%'
            - '%github_password%'

    use_cases.fetch_repo_events.use_case:
        class: UseCases\FetchRepoEvents\UseCase
        arguments: ["@infrastructure.github.event_fetcher"]

    Doctrine\DBAL\Connection:
        class: Doctrine\DBAL\Connection
        factory: ["Doctrine\\DBAL\\DriverManager", "getConnection"]
        arguments:
          - driver: pdo_mysql
            dbname: '%db_name%'
            user: '%db_user%'
            password: '%db_password%'
            host: '%db_host%'
